+incdir+.
+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
../../dut/xswitch64.svp
../../dut/dut_top.sv
../../verification/phase8_coverage/phase8_xsw_transaction.sv
../../verification/phase8_coverage/phase8_xsw_coverage.sv
../../verification/phase8_coverage/phase8_xsw_sequences.sv
../../verification/phase8_coverage/phase8_xsw_test_pkg.sv
../../verification/phase8_coverage/phase8_tbench_top.sv