+incdir+.
+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
../../dut/xswitch64.svp
../../dut/dut_top.sv
../../verification/phase7_scoreboard/phase7_xsw_transaction.sv
../../verification/phase7_scoreboard/phase7_xsw_sequences.sv
../../verification/phase7_scoreboard/phase7_xsw_test_pkg.sv
../../verification/phase7_scoreboard/phase7_tbench_top.sv