+incdir+.
+incdir+$UVM_HOME/src
$UVM_HOME/src/uvm_pkg.sv
../../dut/xswitch64.svp
../../dut/dut_top.sv
../../verification/phase9_testcases/phase9_xsw_transaction.sv
../../verification/phase9_testcases/phase9_xsw_coverage.sv
../../verification/phase9_testcases/phase9_xsw_sequences.sv
../../verification/phase9_testcases/phase9_xsw_test_pkg.sv
../../verification/phase9_testcases/phase9_tbench_top.sv
